apiVersion: apps/v1  # Fixed: added the missing 's' to apps
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # Fixed: changed from matchLables to matchLabels and fixed indentation
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: vivekguvvala/mongodb:v1